### ISSUE TITLE
rekall is broken in updated SIFT

### ISSUE THREAD

**Issue by jsolderitsch** [sans-dfir/sift#138]
The latest version of rekall is 1.6.0 (Gotthard). I can install rekall in Sift 3.0 use the virtualenv method.

After a recent SIFT update, it seems that rekall was updated. But trying to run it leads to:

sansforensics@siftworkstation:/cases$ rekall
Traceback (most recent call last):
  File "/usr/local/bin/rekall", line 7, in <module>
    from rekall.rekal import main
  File "/usr/local/lib/python2.7/dist-packages/rekall/rekal.py", line 39, in <module>
    entry_point.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2301, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 859, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (PyYAML 3.12 (/usr/local/lib/python2.7/dist-packages), Requirement.parse('PyYAML==3.11'))

Looks like a PyYAML version mismatch.

I was running rekall 1.5.2 successfully prior to my recent sift update.

**Comment by ekristen** [comment]
Yes, we are aware that rekall doesn't play nice outside of a virtualenv. 

SIFT is moving to a new method of management and providing updates, at the same time support for Ubuntu 16.04 is being tackled, please take a look at https://github.com/sans-dfir/sift-saltstack

**Comment by jsolderitsch** [comment]
Thanks for the update. May try the new "method" soon.
