### ISSUE TITLE
[CLI] unable to perform installation behind proxy

### ISSUE THREAD

**Issue by jeromeRa** [sans-dfir/sift#161]
Using a fresh Ubuntu 16.04 install and having configured proxy environment variables, apt as well as salt minion proxy settings I am unable to perform an installation using the CLI.
I have observed that proxy settings are ignored and a connection timeout occurs:

connect ETIMEDOUT 192.30.253.116:443
Error: connect ETIMEDOUT 192.30.253.116:443
    at module.exports.__dirname.sendError (/snapshot/Users/ekristen/Development/sift/sift-cli/node_modules/github/lib/index.js:853:19)
    at /snapshot/Users/ekristen/Development/sift/sift-cli/node_modules/github/lib/index.js:864:29
    at callCallback (/snapshot/Users/ekristen/Development/sift/sift-cli/node_modules/github/lib/index.js:728:17)
    at ClientRequest.<anonymous> (/snapshot/Users/ekristen/Development/sift/sift-cli/node_modules/github/lib/index.js:806:17)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at TLSSocket.socketErrorListener (_http_client.js:358:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:191:7)
    at emitErrorNT (net.js:1279:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

Is there any way to add proxy support to the CLI ?

**Comment by ekristen** [comment]
Can you share with my the proxy variables you are specifying? The SIFT CLI tool should already be proxy compliant so long as you are using `HTTP_PROXY`, `http_proxy`, `HTTPS_PROXY`, or `https_proxy` env vars.

**Comment by jeromeRa** [comment]
I had specified lower case proxy env variables http_proxy and https_proxy. Using upper case it all works fine as you suggested.
Thanks for your help.

**Comment by ekristen** [comment]
Good to hear.
