### ISSUE TITLE
[CLI] Install Completed with Failures; Won't Update

### ISSUE THREAD

**Issue by crypticgeek** [sans-dfir/sift#162]
New 16.04 install. Install finished with the following message

`>> Completed with Failures -- Success: 283, Failure: 181
`
How do I figure out what failures were?

Now running sudo sift update fails

```
> sift-cli@1.5.0-beta.0-master.16cfb94
> sift-version: notinstalled


SIFT not installed, unable to update
Error: SIFT not installed, unable to update
    at Object.<anonymous> (/snapshot/Users/ekristen/Development/sift/sift-cli/sift-cli.js:586:13)
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/snapshot/Users/ekristen/Development/sift/sift-cli/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn.module.exports.PromiseSpawn._promiseFulfilled (/snapshot/Users/ekristen/Development/sift/sift-cli/node_modules/bluebird/js/release/generators.js:97:49)
    at Promise.module.exports.Promise._settlePromise (/snapshot/Users/ekristen/Development/sift/sift-cli/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise.module.exports.Promise._settlePromise0 (/snapshot/Users/ekristen/Development/sift/sift-cli/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise.module.exports.Promise._settlePromises (/snapshot/Users/ekristen/Development/sift/sift-cli/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/snapshot/Users/ekristen/Development/sift/sift-cli/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/snapshot/Users/ekristen/Development/sift/sift-cli/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.__dirname.Async.drainQueues (/snapshot/Users/ekristen/Development/sift/sift-cli/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

```

**Comment by ekristen** [comment]
Try this for the time being. 

`apt-get remove python3-xlsxwriter` 

then

`sudo sift install` 

Lets see where we get.

After that you can go into `/var/cache/sift/<version>` and grab all the log files and yaml files and send them to be for further troubleshooting.

**Comment by crypticgeek** [comment]
Looking through the logs myself seems our web proxy is causing a lot of the failures. Thanks!
