### ISSUE TITLE
[cli] Sift not installed

### ISSUE THREAD

**Issue by thierry-fr** [sans-dfir/sift#181]
Hi, first of all thanks for the good job with SIFT.

First, I installed a fresh new Ubuntu 16.04. Then I installed SIFT using SIFT-CLI (sudo sift install --mode=packages-only).

As far as I know everything worked fine and no error were returned.

When I try the command "sudo sift update" I have this error :

sudo sift update
sift-cli@1.5.1-beta.0-master.154cb2f
sift-version: notinstalled

SIFT not installed, unable to update
Error: SIFT not installed, unable to update
    at Object.<anonymous> (/snapshot/sift-cli/sift-cli.js:630:13)
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/snapshot/sift-cli/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn.module.exports.PromiseSpawn._promiseFulfilled (/snapshot/sift-cli/node_modules/bluebird/js/release/generators.js:97:49)
    at Promise.module.exports.Promise._settlePromise (/snapshot/sift-cli/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise.module.exports.Promise._settlePromise0 (/snapshot/sift-cli/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise.module.exports.Promise._settlePromises (/snapshot/sift-cli/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/snapshot/sift-cli/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/snapshot/sift-cli/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.__dirname.Async.drainQueues (/snapshot/sift-cli/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

Effectively, the "/etc" folder only contains "sift-config" file but no "sift-version" file.

I found the SIFT version examining the "sift-config" and recreate an "/etc/sift-version" containing only the version number (v2017.36.0)

That solved my problem...but something went wrong at some time. ;)

EDIT : it seems that using "sift update", a full update is done, even if install was done with the '--mode=packages-only" option.

**Comment by ekristen** [comment]
There's a saltstack.log file under /var/cache/sift/VERSION/ can you upload that please.

**Comment by jdalllasjordan** [comment]
I followed the same process as @thierry-fr and had the same results when trying to run "sift update".  I created the sift-version file as he did and it seemed to work at that point.  I am attaching the saltstack.log file as  you asked for.  Thanks!
[saltstack.log](https://github.com/sans-dfir/sift/files/1357344/saltstack.log)

**Comment by ekristen** [comment]
Looks like your system has fallen victim to having a bad apt repo. Try this ...

```
sudo dpkg --configure -a
```

To resolve.

**Comment by jdalllasjordan** [comment]
Thanks, Erik...I believe that got me going.

**Comment by ekristen** [comment]
Good to hear.

**Comment by ekristen** [comment]
@jdalllasjordan it's come to my attention that there's a bug when it comes to packages-only mode. I'm tracking the issue here https://github.com/sans-dfir/sift/issues/229 and when it is resolved I'll close that problem.
