### ISSUE TITLE
[CLI] Trouble installing due to self signed certs on corp network.

### ISSUE THREAD

**Issue by shadow738** [sans-dfir/sift#212]
I'm having issues installing from a corp network due to self signed certs.  Anyone know a way around this?  Unfortunately, connecting to a non-corp network is not an options since there is not internet access until connected to the corp VPN.

Output from terminal:

> sift-cli@1.5.1-beta.0-master.154cb2f
> sift-version: notinstalled

self signed certificate in certificate chain
Error: self signed certificate in certificate chain
    at module.exports.__dirname.sendError (/snapshot/sift-cli/node_modules/github/lib/index.js:853:19)
    at /snapshot/sift-cli/node_modules/github/lib/index.js:864:29
    at callCallback (/snapshot/sift-cli/node_modules/github/lib/index.js:728:17)
    at ClientRequest.<anonymous> (/snapshot/sift-cli/node_modules/github/lib/index.js:806:17)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at TLSSocket.socketErrorListener (_http_client.js:358:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:191:7)
    at emitErrorNT (net.js:1279:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

Thanks.

**Comment by b1tninja** [comment]
Use at your own risk (beware of potential for MITM):

NODE_TLS_REJECT_UNAUTHORIZED=0 sift install

**Comment by ekristen** [comment]
Yes unfortunately if you are using self-signed certificates the above is about your only option.
