### ISSUE TITLE
vol.py issue

### ISSUE THREAD

**Issue by ben4361** [sans-dfir/sift#221]
vol.py error
# vol.py -f WHIT2008.mem imageinfo
Volatility Foundation Volatility Framework 2.6
Traceback (most recent call last):
  File "/usr/bin/vol.py", line 192, in <module>
    main()
  File "/usr/bin/vol.py", line 149, in main
    registry.register_global_options(config, commands.Command)
  File "/usr/lib/python2.7/dist-packages/volatility/registry.py", line 157, in register_global_options
    for m in get_plugin_classes(cls, True).values():
  File "/usr/lib/python2.7/dist-packages/volatility/registry.py", line 152, in get_plugin_classes
    raise Exception("Object {0} has already been defined by {1}".format(name, plugin))
Exception: Object RegistryItem has already been defined by <class 'volatility.plugins.openioc_scan.RegistryItem'>

**Comment by mark-hallman** [comment]
@ekristen was this actually fixed?   just checking...  -mark

**Comment by ekristen** [comment]
Probably not, unless we disable all community plugins by default there's always going to be conflicts because Volatility doesn't enforce unique command line parameters across plugins. 

The only fix I see is disable by default.
