### ISSUE TITLE
Command: "sudo sift install" fails.

### ISSUE THREAD

**Issue by IntenseMilk** [sans-dfir/sift#244]
Followed the option 2 guide on https://digital-forensics.sans.org/community/downloads:

(1) Running on an Ubuntu 16.04 Machine (from HDD not Virtually)
(2) Went through second step with no issues
(3) sudo install sift output:
```

sudo sift install
> sift-cli@1.5.1-beta.0-master.154cb2f
> sift-version: notinstalled

Installing and configuring SaltStack properly ...

Command failed: apt-get update
W: Target Packages (partner/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list:43 and /etc/apt/sources.list.d/xenial-partner.list:4
W: Target Packages (partner/binary-i386/Packages) is configured multiple times in /etc/apt/sources.list:43 and /etc/apt/sources.list.d/xenial-partner.list:4
W: Target Packages (partner/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:43 and /etc/apt/sources.list.d/xenial-partner.list:4
W: Target Translations (partner/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list:43 and /etc/apt/sources.list.d/xenial-partner.list:4
W: Target Translations (partner/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:43 and /etc/apt/sources.list.d/xenial-partner.list:4
W: Target DEP-11 (partner/dep11/Components-amd64.yml) is configured multiple times in /etc/apt/sources.list:43 and /etc/apt/sources.list.d/xenial-partner.list:4
W: Target DEP-11-icons (partner/dep11/icons-64x64.tar) is configured multiple times in /etc/apt/sources.list:43 and /etc/apt/sources.list.d/xenial-partner.list:4
W: The repository 'cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial Release' does not have a Release file.
E: Failed to fetch cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801)/dists/xenial/main/binary-amd64/Packages  Please use apt-cdrom to make this CD-ROM recognized by APT. apt-get update cannot be used to add new CD-ROMs
E: Some index files failed to download. They have been ignored, or old ones used instead.
W: Target Packages (partner/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list:43 and /etc/apt/sources.list.d/xenial-partner.list:4
W: Target Packages (partner/binary-i386/Packages) is configured multiple times in /etc/apt/sources.list:43 and /etc/apt/sources.list.d/xenial-partner.list:4
W: Target Packages (partner/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:43 and /etc/apt/sources.list.d/xenial-partner.list:4
W: Target Translations (partner/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list:43 and /etc/apt/sources.list.d/xenial-partner.list:4
W: Target Translations (partner/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:43 and /etc/apt/sources.list.d/xenial-partner.list:4
W: Target DEP-11 (partner/dep11/Components-amd64.yml) is configured multiple times in /etc/apt/sources.list:43 and /etc/apt/sources.list.d/xenial-partner.list:4
W: Target DEP-11-icons (partner/dep11/icons-64x64.tar) is configured multiple times in /etc/apt/sources.list:43 and /etc/apt/sources.list.d/xenial-partner.list:4

Error: Command failed: apt-get update
W: Target Packages (partner/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list:43 and /etc/apt/sources.list.d/xenial-partner.list:4
W: Target Packages (partner/binary-i386/Packages) is configured multiple times in /etc/apt/sources.list:43 and /etc/apt/sources.list.d/xenial-partner.list:4
W: Target Packages (partner/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:43 and /etc/apt/sources.list.d/xenial-partner.list:4
W: Target Translations (partner/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list:43 and /etc/apt/sources.list.d/xenial-partner.list:4
W: Target Translations (partner/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:43 and /etc/apt/sources.list.d/xenial-partner.list:4
W: Target DEP-11 (partner/dep11/Components-amd64.yml) is configured multiple times in /etc/apt/sources.list:43 and /etc/apt/sources.list.d/xenial-partner.list:4
W: Target DEP-11-icons (partner/dep11/icons-64x64.tar) is configured multiple times in /etc/apt/sources.list:43 and /etc/apt/sources.list.d/xenial-partner.list:4
W: The repository 'cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial Release' does not have a Release file.
E: Failed to fetch cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801)/dists/xenial/main/binary-amd64/Packages  Please use apt-cdrom to make this CD-ROM recognized by APT. apt-get update cannot be used to add new CD-ROMs
E: Some index files failed to download. They have been ignored, or old ones used instead.
W: Target Packages (partner/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list:43 and /etc/apt/sources.list.d/xenial-partner.list:4
W: Target Packages (partner/binary-i386/Packages) is configured multiple times in /etc/apt/sources.list:43 and /etc/apt/sources.list.d/xenial-partner.list:4
W: Target Packages (partner/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:43 and /etc/apt/sources.list.d/xenial-partner.list:4
W: Target Translations (partner/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list:43 and /etc/apt/sources.list.d/xenial-partner.list:4
W: Target Translations (partner/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:43 and /etc/apt/sources.list.d/xenial-partner.list:4
W: Target DEP-11 (partner/dep11/Components-amd64.yml) is configured multiple times in /etc/apt/sources.list:43 and /etc/apt/sources.list.d/xenial-partner.list:4
W: Target DEP-11-icons (partner/dep11/icons-64x64.tar) is configured multiple times in /etc/apt/sources.list:43 and /etc/apt/sources.list.d/xenial-partner.list:4

    at ChildProcess.exithandler (child_process.js:205:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

As I was searching for a solution, I noticed the saltstack file was requested but my `/var/cache/sift` directory only consists of an empty `cli` directory (`/var/cache/sift/cli`). I did reset my system before checking for the saltstack logfile so that could make a difference but I doubt so considering running the command produces the same results each time it's ran.

Extra stuff:
(1) I did run sudo apt update && dist-upgrade but no change
(2) `sudo sift upgrade` and `sudo sift update` produce the exact same result as listed above.
(3) tried `su root` but can only install sift on a user account
(4) not sure what the command `sudo dpkg --configure -a` does but it was recommended in my research so I tried it with no result
(5) history of commands entered during the installation process up to the initial failure encounter
```
 1977  gpg --keyserver pgp.mit.edu --recv-keys 22598A94
 1978  gpg --verify sift-cli-linux.sha256.asc
 1979  cd ./Downloads/
 1980  gpg --verify sift-cli-linux.sha256.asc
 1981  shasum -a 256 -c sift-cli-linux.sha256.asc
 1982  sha256sum -c sift-cli-linux.sha256.asc
 1983  sudo mv sift-cli-linux /usr/local/bin/sift
 1984  chmod 755 /usr/local/bin/sift
 1985  sift --help
 1977  gpg --keyserver pgp.mit.edu --recv-keys 22598A94
 1978  gpg --verify sift-cli-linux.sha256.asc
 1979  cd ./Downloads/
 1980  gpg --verify sift-cli-linux.sha256.asc
 1981  shasum -a 256 -c sift-cli-linux.sha256.asc
 1982  sha256sum -c sift-cli-linux.sha256.asc
 1983  sudo mv sift-cli-linux /usr/local/bin/sift
 1984  chmod 755 /usr/local/bin/sift
 1985  sift --help
```

Thank you and hope we can fix this error easily because I could not find this specific issue anywhere else!

**Comment by ekristen** [comment]
Looks like your apt is configuring incorrectly which is preventing the CLI from being able to install it's needed packages. 

Check the files listed and remove any duplicate sources. Then try again.

**Comment by marisp27** [comment]
Hi 
I am newbie on  linux and running ubuntu 16.04 on virtual machine. I have installed sift using apt -get command and it is showing in installed aps but is not on desktop or anywhere else. Can you please help?
