### ISSUE TITLE
sift-cli update/upgrade breaks upgrade path

### ISSUE THREAD

**Issue by joshlemon** [sans-dfir/sift#278]
After performing `sudo sift update && sudo sift upgrade`, on the most recent .OVA from the SANS website, followed by a `sudo reboot` any further upgrades\updates using the sift-cli are broken and throw the following error:
```
sift-cli@1.6.1-master.bde3e23
sift-version: v2018.08.0

NOTICE: Fixing incorrect Saltstack configuration.
Installing and configuring Saltstack properly ...


Command failed: apt-get remove -y salt-minion salt-common
E: Held packages were changed and -y was used without --allow-change-held-packages.


Error: Command failed: apt-get remove -y salt-minion salt-common
E: Held packages were changed and -y was used without --allow-change-held-packages.

    at ChildProcess.exithandler (child_process.js:205:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

**Comment by Marwolf** [comment]
Run:
`apt-get remove -y salt-minion salt-common --allow-change-held-packages`

Then:
`sudo sift update`

**Comment by ekristen** [comment]
If there is a new release of the sift cli you can upgrade to that fixes this issue.
