### ISSUE TITLE
Error Upgrading

### ISSUE THREAD

**Issue by gedeon8084** [sans-dfir/sift#296]
When I run the command "sudo sift upgrade" i get the following error

> pagz@siftworkstation:/usr/local/bin$ sudo sift upgrade
> sift-cli@1.5.1-beta.0-master.154cb2f
> sift-version: v2017.36.1-rc2

> downloading v2018.28.0
>> downloading sift-saltstack-v2018.28.0.tar.gz.asc
>> downloading sift-saltstack-v2018.28.0.tar.gz.sha256
>> downloading sift-saltstack-v2018.28.0.tar.gz.sha256.asc
>> downloading sift-saltstack-v2018.28.0.tar.gz
> validating file sift-saltstack-v2018.28.0.tar.gz
> validating signature for sift-saltstack-v2018.28.0.tar.gz.sha256

Unknown ASCII armor type
Error: Unknown ASCII armor type
    at getType (/snapshot/sift-cli/node_modules/openpgp/dist/openpgp.js:12050:11)
    at Object.dearmor [as decode] (/snapshot/sift-cli/node_modules/openpgp/dist/openpgp.js:12252:14)
    at Object.readArmored (/snapshot/sift-cli/node_modules/openpgp/dist/openpgp.js:4642:31)
    at Object.<anonymous> (/snapshot/sift-cli/sift-cli.js:358:35)
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/snapshot/sift-cli/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn.module.exports.PromiseSpawn._promiseFulfilled (/snapshot/sift-cli/node_modules/bluebird/js/release/generators.js:97:49)
    at Promise.module.exports.Promise._settlePromise (/snapshot/sift-cli/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise.module.exports.Promise._settlePromise0 (/snapshot/sift-cli/node_modules/bluebird/js/release/promise.js:614:10)

> 

Any ideas?

**Comment by ekristen** [comment]
Sounds like there was a problem downloading the files. 

I would also ask that you upgrade your SIFT CLI before trying again -- https://github.com/sans-dfir/sift-cli/releases/latest

**Comment by gedeon8084** [comment]
Thanks for your response!
The same error with the latest version:

> pagz@siftworkstation:~/Downloads$ sudo sift upgrade
> sift-cli@1.7.1-master.f1177e4
> sift-version: v2017.36.1-rc2

> downloading v2018.28.0
>> downloading sift-saltstack-v2018.28.0.tar.gz.asc
>> downloading sift-saltstack-v2018.28.0.tar.gz.sha256
>> downloading sift-saltstack-v2018.28.0.tar.gz.sha256.asc
>> downloading sift-saltstack-v2018.28.0.tar.gz
> validating file sift-saltstack-v2018.28.0.tar.gz
> validating signature for sift-saltstack-v2018.28.0.tar.gz.sha256

Unknown ASCII armor type
Error: Unknown ASCII armor type
    at getType (/snapshot/Users/ekristen/Development/sift/sift-cli/node_modules/openpgp/dist/openpgp.js:12050:11)
    at Object.dearmor [as decode] (/snapshot/Users/ekristen/Development/sift/sift-cli/node_modules/openpgp/dist/openpgp.js:12252:14)
    at Object.readArmored (/snapshot/Users/ekristen/Development/sift/sift-cli/node_modules/openpgp/dist/openpgp.js:4642:31)
    at Object.<anonymous> (/snapshot/Users/ekristen/Development/sift/sift-cli/sift-cli.js:390:35)
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/snapshot/Users/ekristen/Development/sift/sift-cli/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn.module.exports.PromiseSpawn._promiseFulfilled (/snapshot/Users/ekristen/Development/sift/sift-cli/node_modules/bluebird/js/release/generators.js:97:49)
    at Promise.module.exports.Promise._settlePromise (/snapshot/Users/ekristen/Development/sift/sift-cli/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise.module.exports.Promise._settlePromise0 (/snapshot/Users/ekristen/Development/sift/sift-cli/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise.module.exports.Promise._settlePromises (/snapshot/Users/ekristen/Development/sift/sift-cli/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise.module.exports.Promise._fulfill (/snapshot/Users/ekristen/Development/sift/sift-cli/node_modules/bluebird/js/release/promise.js:638:18)
    at module.exports (/snapshot/Users/ekristen/Development/sift/sift-cli/node_modules/bluebird/js/release/nodeback.js:42:21)
    at tryToString (fs.js:449:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)

>

**Comment by gedeon8084** [comment]
Just for further information, I tried to perform this action more than 50 times. I don't have internet issues (at least that I am aware of). 
The error appears after 4 seconds of running the command.
Let me know if there is anything else that I can do

**Comment by gedeon8084** [comment]
Initial Problem Solved!
I did as you instructed and..

> go remove /var/cache/sift.

But now, I get the following:

>> Incomplete due to Failures -- Success: 487, Failure: 52

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: colorama
        SLS: sift.python-packages.colorama
        Run#: 172
        Comment: An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
      - ID: construct
        SLS: sift.python-packages.construct
        Run#: 173
        Comment: An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
      - ID: dpapick
        SLS: sift.python-packages.dpapick
        Run#: 174
        Comment: An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
      - ID: distorm3
        SLS: sift.python-packages.distorm3
        Run#: 175
        Comment: An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
      - ID: haystack
        SLS: sift.python-packages.haystack
        Run#: 176
        Comment: An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
      - ID: lxml
        SLS: sift.python-packages.lxml
        Run#: 177
        Comment: An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
      - ID: undefined
        SLS: sift.python-packages.ioc_writer
        Run#: 178
        Comment: One or more requisite failed: sift.python-packages.lxml.lxml
      - ID: pefile
        SLS: sift.python-packages.pefile
        Run#: 179
        Comment: An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
      - ID: pycoin
        SLS: sift.python-packages.pycoin
        Run#: 180
        Comment: An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
      - ID: pysocks
        SLS: sift.python-packages.pysocks
        Run#: 181
        Comment: An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.


Is this a corruptions issue again? I tried re deleting the cache with no luck, always same amount of failures:52.

The error says 

> Python 2 pip module is required

How do i fix that? 


Thanks again!

**Comment by gedeon8084** [comment]
Should I downgrade pip?, trough
`$ pip install `pip==9.0.3`

**Comment by gedeon8084** [comment]
If I do, I get the following error:

> >> Incomplete due to Failures -- Success: 536, Failure: 3

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: sift-python-packages-machinae
        SLS: sift.python-packages.machinae
        Run#: 261
        Comment: Error installing 'machinae': Could not find a `pip` binary
      - ID: undefined
        SLS: sift.python-packages
        Run#: 280
        Comment: One or more requisite failed: sift.python-packages.machinae.sift-python-packages-machinae
      - ID: undefined
        SLS: sift.vm
        Run#: 545
        Comment: One or more requisite failed: sift.python-packages.sift-python-packages

> 
I hope it helps.

**Comment by ekristen** [comment]
```salt-call --versions-report```

**Comment by gedeon8084** [comment]
Here is the report:

> $ salt-call --versions-report
Salt Version:
           Salt: 2017.7.5
 
Dependency Versions:
           cffi: 1.11.0
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: 0.3.8
         PyYAML: 4.1
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.6
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-29-generic
         system: Linux
        version: Ubuntu 16.04 xenial

> 

Let me know if there is anything else I can do.

**Comment by gedeon8084** [comment]
Ok. Problem solved!
In the forum, there was a post by @johnmccash, that gave the solution.
To summarize, after:
`$ pip installpip==9.0.3`
I performed:
`apt-get install python3-pip --reinstall`  
That solved the problem for me.

**Comment by ekristen** [comment]
Great, glad to hear it.
