### ISSUE TITLE
Installation of Sift on Ubuntu 16.04.5 LTS Desktop

### ISSUE THREAD

**Issue by shailu75** [sans-dfir/sift#309]
Hi,

I am trying to Install the Sift-Cli-linux  in Ubuntu 16.04.5 LTS Desktop (64bit)
curl -Lo /usr/local/bin/sift https://github.com/sans-dfir/sift-cli/releases/download/v1.7.1/sift-cli-linux
chmod +x /usr/local/bin/sift

Getting the below error

# sift install
> sift-cli@1.7.1-master.f1177e4
> sift-version: notinstalled

write EPROTO 140478923241280:error:14077419:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert access denied:../deps/openssl/openssl/ssl/s23_clnt.c:769:

Error: write EPROTO 140478923241280:error:14077419:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert access denied:../deps/openssl/openssl/ssl/s23_clnt.c:769:

    at module.exports.__dirname.sendError (/snapshot/Users/ekristen/Development/sift/sift-cli/node_modules/github/lib/index.js:854:19)
    at /snapshot/Users/ekristen/Development/sift/sift-cli/node_modules/github/lib/index.js:865:29
    at callCallback (/snapshot/Users/ekristen/Development/sift/sift-cli/node_modules/github/lib/index.js:728:17)
    at ClientRequest.<anonymous> (/snapshot/Users/ekristen/Development/sift/sift-cli/node_modules/github/lib/index.js:807:17)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at TLSSocket.socketErrorListener (_http_client.js:358:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:191:7)
    at onwriteError (_stream_writable.js:341:10)
    at onwrite (_stream_writable.js:359:5)
    at fireErrorCallbacks (net.js:481:13)
    at TLSSocket.Socket._destroy (net.js:522:3)
    at WriteWrap.afterWrite [as oncomplete] (net.js:816:10)

Kindly Suggest where should be issue.....

Thanks,
Shailu

**Comment by shailu75** [comment]
Hi,
Found some Proxy issue and I have fixed the Issue,

Thanks,
Shailu
