### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by j-ro** [sans-dfir/sift#332]
Hey folks, trying to install on Ubuntu 14.04, getting this error:

```
ubuntu@ip-10-1-0-33:~$ sudo sift install
> sift-cli@1.7.1-master.f1177e4
> sift-version: notinstalled

Installing and configuring SaltStack properly ...

Command failed: apt-get install -y --allow-change-held-packages salt-minion
E: Command line option --allow-change-held-packages is not understood

Error: Command failed: apt-get install -y --allow-change-held-packages salt-minion
E: Command line option --allow-change-held-packages is not understood

    at ChildProcess.exithandler (child_process.js:205:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

apt seems to work fine as far as I can tell, installing other things like curl works. That flag doesn't seem to though, not sure why.

What's the best Ubuntu version to use here, maybe that's the issue? This is for AWS ec2, so currently trying the 14.04 AMI.

**Comment by ekristen** [comment]
14.04 is not supported

**Comment by j-ro** [comment]
Gotcha -- what should I use then? 18.04 didn't work either (read here that wasn't supported). What's the recommended distro?

**Comment by ekristen** [comment]
16.04 is the only supported, 18.04 is being worked on.

**Comment by j-ro** [comment]
Ok great, will try 16.04 then!

**Comment by j-ro** [comment]
Hm, got a lot farther on the install this time, but still failed out. Not quite sure what I'm looking at in terms of how to debug:

```
>> Incomplete due to Failures -- Success: 529, Failure: 11

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: sift-config-terminal-profiles-install
        SLS: sift.config.user.terminal
        Run#: 474
        Comment: Command "dconf load /org/gnome/terminal/ < /usr/share/sift/terminal-profiles.txt" run
      - ID: sift-config-theme-gtk
        SLS: sift.config.user.theme
        Run#: 477
        Comment: Command "gsettings set org.gnome.desktop.interface gtk-theme Arc" run
      - ID: sift-config-theme-icon
        SLS: sift.config.user.theme
        Run#: 478
        Comment: Command "gsettings set org.gnome.desktop.interface icon-theme Arc-Icons" run
      - ID: sift-config-unity-launcher-user
        SLS: sift.config.user.unity
        Run#: 485
        Comment: Command "gsettings set com.canonical.Unity.Launcher launcher-position Bottom" run
      - ID: sift-config-unity-disable-scopes
        SLS: sift.config.user.unity
        Run#: 486
        Comment: Command "gsettings set com.canonical.Unity.Lenses disabled-scopes "['more_suggestions-amazon.scope', 'more_suggestions-u1ms.scope', 'more_suggestions-populartracks.scope', 'music-musicstore.scope', 'more_suggestions-ebay.scope', 'more_suggestions-ubuntushop.scope', 'more_suggestions-skimlinks.scope']"" run
      - ID: sift-config-unity-favorites
        SLS: sift.config.user.unity
        Run#: 487
        Comment: Command "gsettings set com.canonical.Unity.Launcher favorites "['application://gnome-terminal.desktop', 'application://firefox.desktop', 'application://org.gnome.Nautilus.desktop', 'application://unity-control-center.desktop', 'unity://running-apps', 'unity://expo-icon', 'unity://devices']"" run
      - ID: sift-config-unity-icon-size
        SLS: sift.config.user.unity
        Run#: 488
        Comment: Command "dconf write /org/compiz/profiles/unity/plugins/unityshell/icon-size 32" run
      - ID: sift-config-unity-minimize-window
        SLS: sift.config.user.unity
        Run#: 489
        Comment: Command "dconf write /org/compiz/profiles/unity/plugins/unityshell/launcher-minimize-window true" run
      - ID: undefined
        SLS: sift.config.user
        Run#: 490
        Comment: One or more requisite failed: sift.config.user.theme.sift-config-theme-icon, sift.config.user.unity.sift-config-unity-icon-size, sift.config.user.unity.sift-config-unity-favorites, sift.config.user.terminal.sift-config-terminal-profiles-install, sift.config.user.unity.sift-config-unity-launcher-user, sift.config.user.unity.sift-config-unity-disable-scopes, sift.config.user.theme.sift-config-theme-gtk, sift.config.user.unity.sift-config-unity-minimize-window
      - ID: undefined
        SLS: sift.config
        Run#: 547
        Comment: One or more requisite failed: sift.config.user.sift-config-user
```

**Comment by j-ro** [comment]
nevermind, I got it with packages only mode and a python update, thank you!
