### ISSUE TITLE
sift Install issue: Could not find a `pip` binary in virtualenv /opt/rekall 

### ISSUE THREAD

**Issue by sbrendel** [sans-dfir/sift#333]
Hi All,

I try to install sift on an Ubuntu 16.04 system and get the following error message:

>> Incomplete due to Failures -- Success: 532, Failure: 8

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: rekall-virtualenv
        SLS: sift.python-packages.rekall
        Run#: 270
        Comment: An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1870, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1818, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/states/virtualenv_mod.py", line 251, in managed
    before = set(__salt__['pip.freeze'](bin_env=name, user=user, use_vt=use_vt))
  File "/usr/lib/python2.7/dist-packages/salt/modules/pip.py", line 1010, in freeze
    pip_bin = _get_pip_bin(bin_env)
  File "/usr/lib/python2.7/dist-packages/salt/modules/pip.py", line 147, in _get_pip_bin
    raise CommandNotFoundError(msg)
CommandNotFoundError: Could not find a `pip` binary in virtualenv /opt/rekall

The full error message can be found here:

https://pastebin.com/aVzdHwqz

Does anybody know how to fix this error?

Thanks in advance!

Best regards,

Stephan

**Comment by sbrendel** [comment]
I solved it...

In case someone else has the same error message:

virtualenv /opt/rekall/

will install pip in the /opt/rekall directory and thereafter running the install script again will run without any errors.

Best regards,

Stephan
