### ISSUE TITLE
4n6time not working

### ISSUE THREAD

**Issue by bhutch** [sans-dfir/sift#5]
On SIFT 3.0, 4n6time doesn't seem to start up on either an up-to-date sift-bootstrap or the appliance.

e.g.,

$ 4n6time 
WARNING: file already exists but should not: /tmp/_MEI1rJccH/etc/matplotlibrc
/tmp/_MEI1rJccH/matplotlib/__init__.py:611: UserWarning: Could not find matplotlibrc; using defaults
/tmp/_MEI1rJccH/matplotlib/__init__.py:698: UserWarning: could not find rc file; returning defaults
Traceback (most recent call last):
  File "<string>", line 33, in <module>
  File "/build/pyinstaller/PyInstaller/loader/pyi_importers.py", line 270, in load_module
  File "/build/4n/build/4n6time/out00-PYZ.pyz/lib.controller.splashscreen", line 3, in <module>
  File "/build/pyinstaller/PyInstaller/loader/pyi_importers.py", line 270, in load_module
  File "/build/4n/build/4n6time/out00-PYZ.pyz/lib.controller.controller", line 40, in <module>
  File "/build/pyinstaller/PyInstaller/loader/pyi_importers.py", line 270, in load_module
  File "/build/4n/build/4n6time/out00-PYZ.pyz/lib.view.chartview", line 8, in <module>
  File "/build/pyinstaller/PyInstaller/loader/pyi_importers.py", line 270, in load_module
  File "/build/4n/build/4n6time/out00-PYZ.pyz/matplotlib.backends.backend_wxagg", line 20, in <module>
  File "/build/pyinstaller/PyInstaller/loader/pyi_importers.py", line 270, in load_module
  File "/build/4n/build/4n6time/out00-PYZ.pyz/matplotlib.figure", line 18, in <module>
  File "/build/pyinstaller/PyInstaller/loader/pyi_importers.py", line 270, in load_module
  File "/build/4n/build/4n6time/out00-PYZ.pyz/matplotlib.axes", line 14, in <module>
  File "/build/pyinstaller/PyInstaller/loader/pyi_importers.py", line 270, in load_module
  File "/build/4n/build/4n6time/out00-PYZ.pyz/matplotlib.axis", line 10, in <module>
  File "/build/pyinstaller/PyInstaller/loader/pyi_importers.py", line 270, in load_module
  File "/build/4n/build/4n6time/out00-PYZ.pyz/matplotlib.font_manager", line 1325, in <module>
  File "/build/4n/build/4n6time/out00-PYZ.pyz/matplotlib.font_manager", line 1275, in _rebuild
  File "/build/4n/build/4n6time/out00-PYZ.pyz/matplotlib.font_manager", line 962, in __init__
  File "/build/4n/build/4n6time/out00-PYZ.pyz/posixpath", line 68, in join
AttributeError: 'NoneType' object has no attribute 'endswith'

**Comment by socialcred** [comment]
Is 4n6time working or is it still broken?

**Comment by ekristen** [comment]
@socialcred unfortunately this package is severely broken and with the new Plaso coming on the scene, this package will not be fixed anytime soon.
