### ISSUE TITLE
Volatility 2.5 producing errors in latest SIFT 3

### ISSUE THREAD

**Issue by the-IMOL** [sans-dfir/sift#94]
Hello, currently running SIFT3 (combined with REMnux6) and receiving these errors while attempting to run Volatility 2.5. Have there been any other reports or might this be related to combining SIFT3 with REMnux6?

Volatility Foundation Volatility Framework 2.5
Traceback (most recent call last):
  File "/usr/bin/vol.py", line 192, in <module>
    main()
  File "/usr/bin/vol.py", line 149, in main
    registry.register_global_options(config, commands.Command)
  File "/usr/lib/python2.7/dist-packages/volatility/registry.py", line 157, in register_global_options
    for m in get_plugin_classes(cls, True).values():
  File "/usr/lib/python2.7/dist-packages/volatility/registry.py", line 152, in get_plugin_classes
    raise Exception("Object {0} has already been defined by {1}".format(name, plugin))
Exception: Object EditBox has already been defined by <class 'volatility.plugins.gui.editbox.EditBox'>

**Comment by ekristen** [comment]
See https://github.com/sans-dfir/sift/issues/91

SIFT is not tested for compatibility with REMnux.
